sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - node
dist: trusty
before_install:
- openssl aes-256-cbc -K $encrypted_ddb403d004b8_key -iv $encrypted_ddb403d004b8_iv
  -in deploy_key.enc -out deploy_key -d
- chmod 600 deploy_key
- eval `ssh-agent -s`
- ssh-add deploy_key
- git config --global user.name "Travis CI"
- git config --global user.email "xyz.shotao@gmail.com"
script:
- bash ./scripts/deploy.sh
notifications:
  email: false
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
